### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by EpicSteve33** [EpicSteve33/SurvivalGames#13]
- [x] Add grace period unstable (not tested)
- [x] Add grace period stable
- [x] Add option to enable/disable lightning on death
- [x] Fix winner TP to spawn
- [x] Fix Death Match spawn
- [x] Fix Chests
- [x] Add more config features
- [x] Send messages only to people in SG world
- [ ] Add wolfs to VIPs to help fight
- [ ] Create a Genisys branch (after the above is completed)
- [ ] Frost mode like in the movie (at time during the match snow covers map and players die if they contact it)

**Comment by RedEnder** [comment]
Players die from touching snow? in the last TO-DO

**Comment by EpicSteve33** [comment]
Yep like pc

**Comment by RedEnder** [comment]
never seen anyone die from snow on pc

**Comment by EpicSteve33** [comment]
It places snow all around the map forcing players to spawn and if they touch the "frost" they take damage

**Comment by EpicSteve33** [comment]
I have played on a server that had that

**Comment by EpicSteve33** [comment]
It copied the movie but that's why it's last because I don't know how bad it would lag

**Comment by RedEnder** [comment]
How would we spawn the snow?

**Comment by EpicSteve33** [comment]
Idk yet it's just an idea for now

**Comment by RedEnder** [comment]
whats the random chest spawning?

**Comment by EpicSteve33** [comment]
Idk @ImagicalGamer had it on his todo list so I kept it

**Comment by EpicSteve33** [comment]
https://m.youtube.com/watch?v=ywj5qDsixKo

Btw here a video showing the frost don't know how it would work lel

**Comment by EpicSteve33** [comment]
You do all the work

**Comment by RedEnder** [comment]
;'(

**Comment by RedEnder** [comment]
Lots of this stuff doesn't clarify what they mean or it's just not exactly possible

**Comment by EpicSteve33** [comment]
Rip

**Comment by EpicSteve33** [comment]
This issue has not been resolved but we can update the readme when we make progress to our goal

**Comment by EpicSteve33** [comment]
Let's keep this open so we can fix stuff and keep track of them here

**Comment by RedEnder** [comment]
i perfer 60 seconds 2 minutes i too long :'(

**Comment by RedEnder** [comment]
is*

**Comment by RedEnder** [comment]
vip should get Double Health

**Comment by EpicSteve33** [comment]
Ya I might remove that

**Comment by EpicSteve33** [comment]
That's way to op

**Comment by EpicSteve33** [comment]
>:)

**Comment by EpicSteve33** [comment]
>Ender Sucks

>Wow

>What a skrub

**Comment by EpicSteve33** [comment]
Fuck this shit I'm out jk lel

**Comment by EpicSteve33** [comment]
Let's keep this locked because ender sucks

**Comment by EpicSteve33** [comment]
Unlocked FTW

**Comment by EpicSteve33** [comment]
@RedEnder is such a skrub

**Comment by RedEnder** [comment]
k

**Comment by EpicSteve33** [comment]
This plugin is pretty much done
